name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: '18'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
