name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  call-reusable:
    uses: Akashsami4456/test-repo-gha-ak/.github/workflows/child.yaml@main
    with:
      node-version: '18'
    secrets:
      token: ${{ secrets.MY_PAT }}
